### PR TITLE
Add documentation in help format

### PR DESCRIPTION
**Pull request by tessarin**
Hi!

Thank you for this great color scheme. I attempted to add a version of your README file in Vim-help format. This way we can have a options reference right inside Vim.

### CODE REVIEW

**Comment by ghifarit53** [comment]
This is great! Thank you

**Comment by ghifarit53** [comment]
Looks good. gonna merge now

**Comment by ghifarit53** [comment]
@tessarin thank you

**Comment by tessarin** [comment]
Thank you @ghifarit53 !

**Pull request merged**
